apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
  annotations:
    tekton.dev/docker-0: https://index.docker.io/v1/
  namespace: default
type: kubernetes.io/basic-auth
stringData:
  username: krithik2018
  password: dckr_pat_Rb_5TqyvLpX_f9bSyXLJ64v3IGM
