apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: budget-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/KrithikJoshi/makerble-rails-gitops.git"
    targetRevision: HEAD
    path: makerble-rails-gitops\K8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
