apiVersion: v1
kind: Secret
metadata:
  name: repo-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
type: Opaque
stringData:
  url: https://github.com/KrithikJoshi/makerble-assignment.git
  username: KrithikJoshi
  password: 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
